"""add trip_messages table

Revision ID: a8defcdff070
Revises: c5fc768629af
Create Date: 2026-08-08 11:20:30.951893

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a8defcdff070'
down_revision: str | None = 'c5fc768629af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
