"""add tool_cache table

Revision ID: c5fc768629af
Revises: 24df82f10d20
Create Date: 2026-08-08 10:19:40.278752

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

revision: str = 'c5fc768629af'
down_revision: str | None = '24df82f10d20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_cache',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('content_class', sa.String(length=32), nullable=False),
    sa.Column('payload_jsonb', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('tool_cache', schema=None) as batch_op:
        batch_op.create_index('ix_tool_cache_expires_at', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_cache_expires_at')

    op.drop_table('tool_cache')
    # ### end Alembic commands ###
